### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NiLSPACE** [jrsearles/Cassette.Babel#1]
I've been trying to use this in a project I'm working on, but there is no documentation on how to use this.

I've created a class which is identical to the [InsertBabelTranspiler](https://github.com/jrsearles/Cassette.Babel/blob/master/src/Cassette.Babel/InsertBabelTranspiler.cs) class in order to find out if the `Modify` method is even called. When putting a breakpoint there it does get called multiple times, but nothing changes in the output.

I expect 
```JS
const test = () => {};
```

to result in

```JS
var test = function test() {};
```
Is there any documentation where I can find out how to use this and configure the output? It's possible I'm missing something really obvious, I've never used Babel before.

**Comment by jrsearles** [comment]
I've added some documentation to the readme to help you get going. You will need to configure Babel before any output is changed.

For example, if you inject Cassette.Babel.BabelSettings into your Cassette bundle configuration and use `babelSettings.Presets.Add("es2015");` you will get basic es2015 support.
