### ISSUE TITLE
[Need help] Installation

### ISSUE THREAD

**Issue by jonasbg** [jrsearles/Cassette.Babel#2]
Hi - how would you install this? 
I have no experience with Cassette, but I would like to transform ES6 code to ES5 as my MVC app must support IE11.

Do you have an example project I could download?

**Comment by vishalk90** [comment]
> Hi - how would you install this?
> I have no experience with Cassette, but I would like to transform ES6 code to ES5 as my MVC app must support IE11.
> 
> Do you have an example project I could download?

Hey did you find any sample example??

**Comment by jonasbg** [comment]
> > Hi - how would you install this?
> > I have no experience with Cassette, but I would like to transform ES6 code to ES5 as my MVC app must support IE11.
> > Do you have an example project I could download?
> 
> Hey did you find any sample example??

I did not :( I've abandoned this request for now, as I've moved on to another project.
